apiVersion: v2
name: woocommerce-store
description: A Helm chart for a WooCommerce Store (WordPress + MariaDB)
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: mariadb
    version: 12.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
